# we have to subset the graph in this rather clunky way because subsetting
# using as.numeric(as.factor(V(g)$attribute)) somehow breaks the C core of igraph with
# an undocumented error
c_m <- induced.subgraph(m,                                      which(V(m)$country == "Черногория"|
                                                                      V(the_graph)$country == "США"|
                                                                      V(the_graph)$country == "Канада"|
                                                                      V(the_graph)$country == "Россия"|
                                                                      V(the_graph)$country == "Украина"|
                                                                      V(the_graph)$country == "Беларусь"|
                                                                      V(the_graph)$country == "Германия"|
                                                                      V(the_graph)$country == "Чехия"|
                                                                      V(the_graph)$country == "Израиль"|
                                                                      V(the_graph)$country == "Китай"|
                                                                      V(the_graph)$country == "Швейцария"|
                                                                      V(the_graph)$country == "Великобритания"|
                                                                      V(the_graph)$country == "Эстония"|
                                                                      V(the_graph)$country == "Латвия"|
                                                                      V(the_graph)$country == "Литва"|
                                                                      V(the_graph)$country == "Финляндия"|
                                                                      V(the_graph)$country == "Польша"|
                                                                      V(the_graph)$country == "Нидерланды"|
                                                                      V(the_graph)$country == "Швеция"|
                                                                      V(the_graph)$country == "Франция"|
                                                                      V(the_graph)$country == "Кипр"|
                                                                      V(the_graph)$country == "Австрия"|
                                                                      V(the_graph)$country == "Испания"|
                                                                      V(the_graph)$country == "Венгрия"|
                                                                      V(the_graph)$country == "Норвегия"|
                                                                      V(the_graph)$country == "Дания"|
                                                                      V(the_graph)$country == "Ирландия"|
                                                                      V(the_graph)$country == "Мальта"|
                                                                      V(the_graph)$country == "Азербайджан"|
                                                                      V(the_graph)$country == "Узбекистан"|
                                                                      V(the_graph)$country == "Армения"|
                                                                      V(the_graph)$country == "Молдова"|
                                                                      V(the_graph)$country == "Туркменистан"|
                                                                      V(the_graph)$country == "Таджикистан"|
                                                                      V(the_graph)$country == "Кыргызстан"|
                                                                      V(the_graph)$country == "Казахстан"|
                                                                      V(the_graph)$country == "Болгария"|
                                                                      V(the_graph)$country == "Япония"|
                                                                      V(the_graph)$country == "Турция"|
                                                                      V(the_graph)$country == "Сингапур"|
                                                                      V(the_graph)$country == "Турция"|
                                                                      V(the_graph)$country == "Мальта"|
                                                                      V(the_graph)$country == "Австралия"|
                                                                      V(the_graph)$country == "ОАЭ"|
                                                                      V(the_graph)$country == "Сингапур"|
                                                                      V(the_graph)$country == "Италия"|
                                                                      V(the_graph)$country == "Марокко"|
                                                                      V(the_graph)$country == "Тайланд"|
                                                                      V(the_graph)$country == "Шри-Ланка"|
                                                                      V(the_graph)$country == "Андорра"|
                                                                    V(the_graph)$country == "Люксембург"|
                                                                    V(the_graph)$country == "Греция"))
